main_collection=[
                {
                    "name":"Google",
                    "list":[
                        {
                            "sitename":"Google",
                            "description":"",
                            "href":"https://www.google.com/",
                            "iconpath":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Google_Search_app_icon_on_the_Google_Play_Store_2014-05-04_17-48.png"
                        },
                        {
                            "sitename":"Gmail",
                            "description":"Booru",
                            "href":"https://mail.google.com/mail/u/0/",
                            "iconpath":"https://freepngimg.com/save/66537-logo-account-google-email-gmail-free-png-hq/512x512"
                        },
                        {
                            "sitename":"Calendar",
                            "description":"Booru",
                            "href":"https://calendar.google.com/",
                            "iconpath":"https://www.freeiconspng.com/uploads/google-calendar-icon-png-26.png"
                        },
                        {
                            "sitename":"Sheets",
                            "description":"Booru",
                            "href":"https://sheets.google.com/",
                            "iconpath":"https://freepngimg.com/save/58605-google-angle-symbol-apps-drive-forms-green/512x512"
                        },
                        {
                            "sitename":"YouTube",
                            "description":"Booru",
                            "href":"https://youtube.com",
                            "iconpath":"https://youtube.com/favicon.ico"
                        },
                        {
                            "sitename":"Drive",
                            "description":"Booru",
                            "href":"https://drive.google.com/drive/",
                            "iconpath":"https://drive.google.com/drive/favicon.ico"
                        },
                        {
                            "sitename":"Gemini",
                            "description":"Booru",
                            "href":"https://gemini.google.com/",
                            "iconpath":"https://www.gstatic.com/lamda/images/gemini_favicon_b0ca051193f92ba9f912679dcf95b0efa9f201b6.svg"
                        },

                    ]
                },
                {
                    "name":"Microsoft",
                    "list":[
                        {
                            "sitename":"Bing",
                            "description":"",
                            "href":"https://www.bing.com/",
                            "iconpath":"https://www.bing.com/favicon.ico"
                        },
                        {
                            "sitename":"Office",
                            "description":"",
                            "href":"https://www.office.com/",
                            "iconpath":"https://res.cdn.office.net/officehub/images/content/images/favicon_m365-31d62b976c.ico"
                        },
                        {
                            "sitename":"OneDrive",
                            "description":"",
                            "href":"https://onedrive.live.com/",
                            "iconpath":"https://onedrive.live.com/favicon.ico"
                        },
                        {
                            "sitename":"Outlook",
                            "description":"",
                            "href":"https://outlook.office365.com/mail/",
                            "iconpath":"https://iconape.com/wp-content/files/dj/352389/png/352389.png"
                        },
                        {
                            "sitename":"Teams",
                            "description":"",
                            "href":"https://teams.microsoft.com/",
                            "iconpath":"https://preview.redd.it/if-ms-teams-was-made-back-in-2010-feel-free-to-give-v0-p0t9kblgowca1.png?width=1080&crop=smart&auto=webp&s=753aa0346d3a2eec80fc705fb210c86582e780a4"
                        },
                        {
                            "sitename":"Copilot",
                            "description":"",
                            "href":"https://www.bing.com/chat",
                            "iconpath":"https://www.bing.com/sa/simg/favicon-cplt.ico"
                        },
                    ]
                },
                {
                    "name":"Social",
                    "list":[
                        {
                            "sitename":"WhatsApp",
                            "description":"",
                            "href":"https://web.whatsapp.com/",
                            "iconpath":"https://www.binarytattoo.com/wp-content/uploads/2016/04/Whatsapp-Icon-Logo.png"
                        },
                        {
                            "sitename":"Discord",
                            "description":"",
                            "href":"https://discord.com/channels/@me",
                            "iconpath":"https://preview.redd.it/made-some-frutiger-aero-icons-for-my-desktop-planning-to-v0-ibacjcu92q7c1.png?width=1024&format=png&auto=webp&s=4f744c07c60e9ddf836a3773dacf141f80405059"
                        },
                        {
                            "sitename":"Twitter",
                            "description":"",
                            "href":"https://twitter.com/home",
                            "iconpath":"https://cdn.icon-icons.com/icons2/2890/PNG/512/apps_social_media_twitter_tweet_logo_bird_animal_social_network_icon_182711.png"
                        },
                        {
                            "sitename":"Reddit",
                            "description":"",
                            "href":"https://reddit.com/",
                            "iconpath":"https://iconape.com/wp-content/files/rq/93022/svg/reddit.svg"
                        },
                        {
                            "sitename":"TikTok",
                            "description":"",
                            "href":"https://www.tiktok.com",
                            "iconpath":"https://www.tiktok.com/favicon.ico"
                        },
                        {
                            "sitename":"Instagram",
                            "description":"",
                            "href":"https://www.instagram.com/",
                            "iconpath":"https://freelogopng.com/images/all_img/1658589057old-instagram-logo.png"
                        },
                    ]
                },
                {
                    "name":"Wikipedia",
                    "list":[
                        {
                            "sitename":"Wikipedia",
                            "description":"",
                            "href":"https://www.wikipedia.org/",
                            "iconpath":"https://www.wikipedia.org/favicon.ico"
                        },
                        {
                            "sitename":"Wikitionary",
                            "description":"",
                            "href":"https://www.wiktionary.org/",
                            "iconpath":"https://www.wiktionary.org/favicon.ico"
                        },
                        {
                            "sitename":"Wikia",
                            "description":"",
                            "href":"https://www.fandom.com/",
                            "iconpath":"https://www.fandom.com/favicon.ico"
                        },
                        {
                            "sitename":"Miraheze",
                            "description":"",
                            "href":"https://miraheze.org/",
                            "iconpath":"https://miraheze.org/img/favicon.ico"
                        },
                    ]
                },
                {
                    "name":"Weather",
                    "list":[
                        {
                            "sitename":"Ventusky Maps",
                            "description":"",
                            "href":"https://www.ventusky.com/",
                            "iconpath":"https://www.ventusky.com/favicon.ico"
                        },
                        {
                            "sitename":"lightningmaps.org",
                            "description":"",
                            "href":"https://www.lightningmaps.org/",
                            "iconpath":"https://www.lightningmaps.org/Images/favicon.ico"
                        },
                        {
                            "sitename":"IQAir",
                            "description":"",
                            "href":"https://www.iqair.com/",
                            "iconpath":"https://www.iqair.com/favicon.ico"
                        },
                    ]
                },
                {
                    "name":"Linguistics",
                    "list":[
                        {
                            "sitename":"jisho.org",
                            "description":"",
                            "href":"https://jisho.org/",
                            "iconpath":"https://assets.jisho.org/assets/favicon-062c4a0240e1e6d72c38aa524742c2d558ee6234497d91dd6b75a182ea823d65.ico"
                        },
                    ]
                },
                {
                    "name":"Mathematics",
                    "list":[
                        {
                            "sitename":"Wolfram Alpha",
                            "description":"",
                            "href":"https://www.wolframalpha.com/",
                            "iconpath":"https://www.wolframalpha.com/favicon.ico"
                        },
                        {
                            "sitename":"Desmos Graph Calc",
                            "description":"",
                            "href":"https://www.desmos.com/calculator",
                            "iconpath":"https://www.desmos.com/favicon.ico"
                        },
                        {
                            "sitename":"DerivativeCalc",
                            "description":"",
                            "href":"https://www.derivative-calculator.net/",
                            "iconpath":"https://www.derivative-calculator.net/favicon.ico"
                        },
                        {
                            "sitename":"IntegralCalc",
                            "description":"",
                            "href":"https://www.integral-calculator.com/",
                            "iconpath":"https://www.integral-calculator.com/favicon.ico"
                        },
                    ]
                },
                {
                    "name":"Games",
                    "list":[
                        {
                            "sitename":"Steam",
                            "description":"",
                            "href":"https://store.steampowered.com/",
                            "iconpath":"https://store.steampowered.com/favicon.ico"
                        },
                        {
                            "sitename":"GameBanana",
                            "description":"",
                            "href":"https://www.gamebanana.com/",
                            "iconpath":"https://images.gamebanana.com/static/img/favicon/64x64.png"
                        },
                    ]
                },
                {
                    "name":"漫画",
                    "list":[
                        {
                            "sitename":"Danbooru",
                            "description":"",
                            "href":"hubs/danbooru/index.html",
                            "iconpath":"https://danbooru.donmai.us/packs/static/public/images/danbooru-logo-128x128-ea111b6658173e847734.png"
                        },
                    ]
                },

                ];
